[2021-05-21 15:37:45,807] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 15:37:48,295] [ERROR] [stock_analysis] [app:1891] - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: stock

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/PycharmProjects/Proj_een065-master/stock_analysis/routes.py", line 16, in home
    stocks = Stock.query.order_by(Stock.name).all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2685, in all
    return self._iter().all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2820, in _iter
    result = self.session.execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: stock
[SQL: SELECT stock.id AS stock_id, stock.name AS stock_name, stock.number_of_shares AS stock_number_of_shares 
FROM stock ORDER BY stock.name]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2021-05-21 15:37:48,313] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 15:37:48] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2021-05-21 15:38:00,472] [ERROR] [stock_analysis] [app:1891] - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: stock

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/PycharmProjects/Proj_een065-master/stock_analysis/routes.py", line 16, in home
    stocks = Stock.query.order_by(Stock.name).all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2685, in all
    return self._iter().all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2820, in _iter
    result = self.session.execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: stock
[SQL: SELECT stock.id AS stock_id, stock.name AS stock_name, stock.number_of_shares AS stock_number_of_shares 
FROM stock ORDER BY stock.name]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2021-05-21 15:38:00,473] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 15:38:00] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2021-05-21 15:38:00,474] [CRITICAL] [stock_analysis] [load_database:17] - The website seems to be running. Please stop it and run this file again.
[2021-05-21 15:38:10,051] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 15:38:13,217] [ERROR] [stock_analysis] [app:1891] - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: stock

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/PycharmProjects/Proj_een065-master/stock_analysis/routes.py", line 16, in home
    stocks = Stock.query.order_by(Stock.name).all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2685, in all
    return self._iter().all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2820, in _iter
    result = self.session.execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: stock
[SQL: SELECT stock.id AS stock_id, stock.name AS stock_name, stock.number_of_shares AS stock_number_of_shares 
FROM stock ORDER BY stock.name]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2021-05-21 15:38:13,223] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 15:38:13] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2021-05-21 15:38:15,033] [ERROR] [stock_analysis] [app:1891] - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: stock

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/PycharmProjects/Proj_een065-master/stock_analysis/routes.py", line 16, in home
    stocks = Stock.query.order_by(Stock.name).all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2685, in all
    return self._iter().all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2820, in _iter
    result = self.session.execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: stock
[SQL: SELECT stock.id AS stock_id, stock.name AS stock_name, stock.number_of_shares AS stock_number_of_shares 
FROM stock ORDER BY stock.name]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2021-05-21 15:38:15,034] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 15:38:15] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2021-05-21 15:38:21,066] [ERROR] [stock_analysis] [app:1891] - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: stock

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/PycharmProjects/Proj_een065-master/stock_analysis/routes.py", line 16, in home
    stocks = Stock.query.order_by(Stock.name).all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2685, in all
    return self._iter().all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2820, in _iter
    result = self.session.execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: stock
[SQL: SELECT stock.id AS stock_id, stock.name AS stock_name, stock.number_of_shares AS stock_number_of_shares 
FROM stock ORDER BY stock.name]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2021-05-21 15:38:21,067] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 15:38:21] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2021-05-21 15:49:29,662] [ERROR] [stock_analysis] [app:1891] - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: stock

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/macbook/PycharmProjects/Proj_een065-master/stock_analysis/routes.py", line 16, in home
    stocks = Stock.query.order_by(Stock.name).all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2685, in all
    return self._iter().all()
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2820, in _iter
    result = self.session.execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1929, in _handle_dbapi_exception
    util.raise_(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/macbook/opt/miniconda3/envs/Proj_een065-master/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 692, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: stock
[SQL: SELECT stock.id AS stock_id, stock.name AS stock_name, stock.number_of_shares AS stock_number_of_shares 
FROM stock ORDER BY stock.name]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2021-05-21 15:49:29,665] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 15:49:29] "[35m[1mGET / HTTP/1.1[0m" 500 -
[2021-05-21 15:58:13,775] [INFO] [stock_analysis] [load_database:25] - previous DB file removed
[2021-05-21 15:58:14,593] [INFO] [stock_analysis] [load_database:106] - Finalized - database created successfully!
[2021-05-21 16:00:06,332] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:00:07,871] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:00:07] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:00:07,895] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:00:07] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
[2021-05-21 16:00:07,896] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:00:07] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:03:35,632] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:03:35] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:03:35,717] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:03:35] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:03:35,725] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:03:35] "[37mGET /static/main.js HTTP/1.1[0m" 200 -
[2021-05-21 16:03:36,244] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:03:36] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[2021-05-21 16:04:08,514] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:04:11,812] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:04:11] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:04:11,836] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:04:11] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:04:11,839] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:04:11] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:04:57,571] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:05:03,271] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:05:03] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:05:03,294] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:05:03] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:05:03,295] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:05:03] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:05:30,465] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:05:30] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:05:30,493] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:05:30] "[36mGET /static/main.css HTTP/1.1[0m" 304 -
[2021-05-21 16:05:30,494] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:05:30] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:05:33,358] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:05:33] "[36mGET /static/main.css HTTP/1.1[0m" 304 -
[2021-05-21 16:09:50,899] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:09:54,813] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:09:54] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:09:54,854] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:09:54] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:09:54,858] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:09:54] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:10:18,820] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:10:19,928] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:10:19] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:10:19,966] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:10:19] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:10:19,969] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:10:19] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:12:09,483] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:12:12,109] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:12] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:12:12,136] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:12] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:12:12,141] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:12] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:12:19,570] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:19] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:12:19,610] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:19] "[36mGET /static/main.css HTTP/1.1[0m" 304 -
[2021-05-21 16:12:19,617] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:19] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:12:41,534] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:41] "[37mGET /home HTTP/1.1[0m" 200 -
[2021-05-21 16:12:41,577] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:41] "[36mGET /static/main.css HTTP/1.1[0m" 304 -
[2021-05-21 16:12:41,581] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:41] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:12:43,914] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:43] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:12:43,955] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:43] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:12:43,960] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:43] "[36mGET /static/main.css HTTP/1.1[0m" 304 -
[2021-05-21 16:12:50,785] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:50] "[37mGET /about HTTP/1.1[0m" 200 -
[2021-05-21 16:12:50,824] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:50] "[36mGET /static/main.css HTTP/1.1[0m" 304 -
[2021-05-21 16:12:50,832] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:50] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:12:54,975] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:54] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:12:55,020] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:55] "[36mGET /static/main.css HTTP/1.1[0m" 304 -
[2021-05-21 16:12:55,022] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:12:55] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:13:23,202] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:13:23] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:13:23,264] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:13:23] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:13:23,268] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:13:23] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:14:35,822] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:14:38,108] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:14:38] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:14:38,159] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:14:38] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:14:38,162] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:14:38] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:14:51,104] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:15:01,039] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:15:04,525] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:15:04] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:15:04,547] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:15:04] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:15:04,548] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:15:04] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:15:34,934] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:15:41,271] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:15:41] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:15:41,299] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:15:41] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:15:41,308] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:15:41] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:16:31,398] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:16:31] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:16:31,412] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:16:31] "[37mGET /static/main.css HTTP/1.1[0m" 200 -
[2021-05-21 16:16:31,413] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:16:31] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:16:38,136] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:16:38] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:16:38,150] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:16:38] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:16:38,151] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:16:38] "[36mGET /static/main.css HTTP/1.1[0m" 304 -
[2021-05-21 16:17:25,678] [INFO] [werkzeug] [_internal:113] -  * Running on http://localhost:5000/ (Press CTRL+C to quit)
[2021-05-21 16:17:27,469] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:17:27] "[37mGET / HTTP/1.1[0m" 200 -
[2021-05-21 16:17:27,482] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:17:27] "[36mGET /static/main.js HTTP/1.1[0m" 304 -
[2021-05-21 16:17:27,483] [INFO] [werkzeug] [_internal:113] - 127.0.0.1 - - [21/May/2021 16:17:27] "[36mGET /static/main.css HTTP/1.1[0m" 304 -
